run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/imlargo/go-api
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: false
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100
    statements: 60
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 4
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - nestif
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
    - path: cmd/
      linters:
        - gochecknoinits
    - text: "weak cryptographic primitive"
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0